### PR TITLE
Add support for an initial offset

### PR DESCRIPTION
**Pull request by twodayslate**
This helps for user onboarding and adds some discoverability.

### CODE REVIEW

**Comment by fatbobman** [comment]
Very good idea. Really helpful for onboarding.
Would it be possible to add a use case to the demo code for others to use.

**Comment by twodayslate** [comment]
@fatbobman An example has been included in the demo. Would you like it separate?

**Comment by twodayslate** [comment]
@fatbobman Should I be using resetStatus intead of forcing offset = 0? 

https://github.com/fatbobman/SwipeCell/compare/main...twodayslate:SwipeCell:initial_offset

**Comment by fatbobman** [comment]
You decide.

**Comment by twodayslate** [comment]
@fatbobman It should probably be resetStatus()

Any thoughts on improving the initial state? I'm still investigating the code but it might be better to set an initial status and then reset.

**Comment by fatbobman** [comment]
It might be better to use resetStatus

**Pull request merged**
